version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redis-container
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: fastapi-container
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

  worker:
    build: .
    container_name: celery-worker
    command: celery -A tasks.celery_app worker --loglevel=info
    volumes:
      - ./api:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

volumes:
  mongo-data:
